"""update users for firebase

Revision ID: 878e59e8bf86
Revises: 6e9170ed4644
Create Date: 2025-11-21 06:20:49.144415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878e59e8bf86'
down_revision: Union[str, Sequence[str], None] = '6e9170ed4644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column('provider_id', sa.String(length=255), nullable=True)
    )
    op.create_unique_constraint(None, 'users', ['provider_id'])

    op.alter_column(
        'users',
        'auth_provider',
        existing_type=sa.String(length=32),
        nullable=False,
        server_default='firebase',
    )

    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )

    op.alter_column(
        'users',
        'auth_provider',
        existing_type=sa.String(length=32),
        nullable=True,
        server_default=None,
    )

    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'provider_id')
    # ### end Alembic commands ###
